source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorMaskingButton_Example', :exclusive => true do
  pod 'ColorMaskingButton', :path => '../'
  pod 'PocketSVG'
end

target 'ColorMaskingButton_Tests', :exclusive => true do
  pod 'ColorMaskingButton', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
